package updater

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"ryoku-cli/internal/sys"
)

// the shape limine-snapper-sync generates (comments and paths trimmed).
const limineFixture = `timeout: 3
default_entry: Ryoku Linux/linux
/Ryoku Linux
    //linux
        comment: kernel-id=linux
        cmdline: quiet root=UUID=x rootflags=subvol=@ rw
//Snapshots
    ### Auto-generated by limine-snapper-sync
    ///2026-09-03 14:07:46
        comment: inotify-tools
        ////linux
            comment: kernel-id=linux
            protocol: efi
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/570/snapshot rw
        ////linux-cachyos
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/570/snapshot rw
    ///2026-09-02 21:00:00
        ////linux
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/565/snapshot rw
`

const voidLimineFixture = `default_entry: Ryoku Linux/linux6.12
/Ryoku Linux
    //linux6.12
        comment: Kernel version: 6.12.21_1
        comment: kernel-id=linux6.12
        protocol: linux
        path: boot():/vmlinuz-6.12.21_1
        module_path: boot():/initramfs-6.12.21_1.img
        cmdline: root=UUID=x rootflags=subvol=@ rw
    //Snapshots
        ### Auto-generated by limine-snapper-sync
        ///2026-10-10 02:53:22
            comment: ryoku-update
            ////linux6.12
                comment: Kernel version: 6.12.21_1
                comment: kernel-id=linux6.12
                protocol: linux
                path: boot():/limine_history/vmlinuz-6.12.21_1_sha256_deadbeef
                module_path: boot():/limine_history/initramfs-6.12.21_1.img_sha256_deadbeef
                cmdline: root=UUID=x rootflags=subvol=/@snapshots/1362/snapshot rw
`

func TestSnapshotEntryPathFindsTheNestedEntry(t *testing.T) {
	if got := snapshotEntryPath(limineFixture, "570"); got != "Snapshots/2026-09-03 14:07:46/linux" {
		t.Fatalf("570 -> %q", got)
	}
	if got := snapshotEntryPath(limineFixture, "565"); got != "Snapshots/2026-09-02 21:00:00/linux" {
		t.Fatalf("565 -> %q", got)
	}
	if got := snapshotEntryPath(limineFixture, "999"); got != "" {
		t.Fatalf("unknown snapshot must not match, got %q", got)
	}
	// a subvol match outside //Snapshots (the live entry) never counts
	if got := snapshotEntryPath("//Live\n    ///x\n        ////linux\n            cmdline: rootflags=subvol=/@snapshots/570/snapshot\n", "570"); got != "" {
		t.Fatalf("entry outside Snapshots matched: %q", got)
	}
}

func TestSnapshotEntryPathFindsVoidLinuxEntry(t *testing.T) {
	if got := snapshotEntryPath(voidLimineFixture, "1362"); got != "Snapshots/2026-10-10 02:53:22/linux6.12" {
		t.Fatalf("1362 -> %q", got)
	}
}

// #291: arming the guard records the channel the box tracked before the update,
// so the revert can tell the user how to get back onto updates (`ryoku track
// <channel>`) rather than leaving them pinned to the reverted release tag.
func TestArmBootGuardRecordsChannel(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("RYOKU_REPO", "")
	t.Setenv("XDG_STATE_HOME", filepath.Join(home, ".local", "state"))
	t.Setenv("RYOKU_HOST_PKGMGR", "pacman")
	t.Setenv("XDG_CONFIG_HOME", filepath.Join(home, ".config"))

	dir := t.TempDir()
	oldPending, oldBootOK := pendingFile, bootOKDir
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	t.Cleanup(func() { pendingFile, bootOKDir = oldPending, oldBootOK })
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}

	conf := filepath.Join(dir, "pacman.conf")
	if err := os.WriteFile(conf, []byte("[options]\n\n[ryoku]\nServer = "+sys.ChannelServer("stable")+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	rel := filepath.Join(dir, "ryoku-release")
	if err := os.WriteFile(rel, []byte("RELEASE=v0.75.3-beta.20\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	oldConf, oldRel := sys.PacmanConf, sys.ReleaseFile
	sys.PacmanConf, sys.ReleaseFile = conf, rel
	t.Cleanup(func() { sys.PacmanConf, sys.ReleaseFile = oldConf, oldRel })

	t.Setenv("RYOKU_UPDATE_FROM", "v0.63.1-beta.19")
	armBootGuard("")

	raw, err := os.ReadFile(pendingFile)
	if err != nil {
		t.Fatalf("pending marker not written: %v", err)
	}
	var p pendingUpdate
	if err := json.Unmarshal(raw, &p); err != nil {
		t.Fatal(err)
	}
	if p.Channel != "stable" {
		t.Fatalf("recorded channel = %q, want stable", p.Channel)
	}
	if p.From != "v0.63.1-beta.19" || p.To != "v0.75.3-beta.20" {
		t.Fatalf("From/To = %q/%q, want v0.63.1-beta.19/v0.75.3-beta.20", p.From, p.To)
	}
}

func setupXBPSReleaseHost(t *testing.T) string {
	t.Helper()
	home := isolateHome(t)
	t.Setenv("RYOKU_HOST_PKGMGR", "xbps")
	t.Setenv("RYOKU_HOST_PKG_TABLE", filepath.Join(home, "void.tsv"))
	t.Setenv("RYOKU_RELEASE_BASE", "")
	if err := os.WriteFile(filepath.Join(home, "void.tsv"), []byte("arch\tvoid\tlanes\tnotes\nryoku-desktop\tryoku-desktop\tdesktop\trepo=ryoku\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	bin := filepath.Join(home, "bin")
	if err := os.MkdirAll(bin, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(bin, "xbps-query"), []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin)

	dir := t.TempDir()
	configDir := filepath.Join(dir, "xbps.d")
	shipped := filepath.Join(dir, "20-ryoku.conf")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(shipped, []byte("repository=https://repo.ryoku.dev/stable/void/x86_64\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("RYOKU_XBPS_CONFIG_DIR", configDir)
	t.Setenv("RYOKU_XBPS_SHIPPED_CONFIG", shipped)

	release := filepath.Join(dir, "ryoku-release")
	if err := os.WriteFile(release, []byte("RELEASE=v0.75.3-beta.20\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	oldRelease, oldIntent := sys.ReleaseFile, sys.ChannelIntentFile
	sys.ReleaseFile = release
	sys.ChannelIntentFile = filepath.Join(dir, "channel-intent")
	t.Cleanup(func() {
		sys.ReleaseFile = oldRelease
		sys.ChannelIntentFile = oldIntent
	})
	return dir
}

func captureXBPSMove(t *testing.T) *[][]string {
	t.Helper()
	var calls [][]string
	oldSync, oldSet, oldServed := syncRepoForMove, ryokuSetForMove, servedSetForMove
	oldInstalled, oldSplit, oldMove := pkgInstalledForMove, splitMetaInstalled, runRyokuMove
	syncRepoForMove = func(bool) error { return nil }
	ryokuSetForMove = func() ([]string, error) { return []string{"ryoku-desktop", "ryogami"}, nil }
	servedSetForMove = func() map[string]bool { return map[string]bool{"ryoku-desktop": true, "ryogami": true} }
	pkgInstalledForMove = func(string) bool { return true }
	splitMetaInstalled = func(string) bool { return false }
	runRyokuMove = func(set []string) error {
		calls = append(calls, ryokuMoveArgs(set))
		return nil
	}
	t.Cleanup(func() {
		syncRepoForMove, ryokuSetForMove, servedSetForMove = oldSync, oldSet, oldServed
		pkgInstalledForMove, splitMetaInstalled, runRyokuMove = oldInstalled, oldSplit, oldMove
	})
	return &calls
}

func TestArmBootGuardOnXBPSReleaseChange(t *testing.T) {
	dir := setupXBPSReleaseHost(t)
	oldPending, oldBootOK := pendingFile, bootOKDir
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	t.Cleanup(func() { pendingFile, bootOKDir = oldPending, oldBootOK })
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}

	t.Setenv("RYOKU_UPDATE_FROM", "v0.63.1-beta.19")
	armBootGuard("1362")

	raw, err := os.ReadFile(pendingFile)
	if err != nil {
		t.Fatalf("pending marker not written: %v", err)
	}
	var p pendingUpdate
	if err := json.Unmarshal(raw, &p); err != nil {
		t.Fatal(err)
	}
	if p.From != "v0.63.1-beta.19" || p.To != "v0.75.3-beta.20" || p.Channel != "stable" || p.Snapshot != "1362" {
		t.Fatalf("pending marker = %+v", p)
	}
}

func TestRollbackToReleaseRunsXBPSMove(t *testing.T) {
	setupXBPSReleaseHost(t)
	calls := captureXBPSMove(t)
	oldUpdate := runChannelUpdate
	runChannelUpdate = func() error {
		_, err := moveRyokuSetToChannel()
		return err
	}
	t.Cleanup(func() { runChannelUpdate = oldUpdate })

	if err := Rollback([]string{"--to", "v0.63.1-beta.19"}); err != nil {
		t.Fatal(err)
	}
	want := []string{"env", "RYOKU_MANAGED_UPDATE=1", "xbps-install", "-Sfy", "ryoku-desktop", "ryogami"}
	if len(*calls) != 1 || !reflect.DeepEqual((*calls)[0], want) {
		t.Fatalf("XBPS move calls = %v, want [%v]", *calls, want)
	}
}

func TestBootGuardRevertsXBPSRelease(t *testing.T) {
	dir := setupXBPSReleaseHost(t)
	calls := captureXBPSMove(t)
	oldPending, oldBootOK, oldNotice, oldUID := pendingFile, bootOKDir, noticeFile, effectiveUID
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	noticeFile = filepath.Join(bootOKDir, "notice.json")
	effectiveUID = func() int { return 0 }
	t.Cleanup(func() {
		pendingFile, bootOKDir, noticeFile, effectiveUID = oldPending, oldBootOK, oldNotice, oldUID
	})
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}
	p := pendingUpdate{
		From: "v0.63.1-beta.19", To: "v0.75.3-beta.20", Channel: "stable",
		Snapshot: "1362", ArmedBoot: "earlier-boot", Boots: 1,
	}
	body, _ := json.Marshal(p)
	if err := os.WriteFile(pendingFile, body, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := BootGuard(nil); err != nil {
		t.Fatal(err)
	}
	want := []string{"env", "RYOKU_MANAGED_UPDATE=1", "xbps-install", "-Sfy", "ryoku-desktop", "ryogami"}
	if len(*calls) != 1 || !reflect.DeepEqual((*calls)[0], want) {
		t.Fatalf("XBPS revert calls = %v, want [%v]", *calls, want)
	}
	if _, err := os.Stat(pendingFile); !os.IsNotExist(err) {
		t.Fatalf("pending marker survived successful revert: %v", err)
	}
	raw, err := os.ReadFile(noticeFile)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), `"action": "reverted"`) || !strings.Contains(string(raw), "Void untouched") {
		t.Fatalf("revert notice = %s", raw)
	}
}
