package updater

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"ryoku-cli/internal/host"
	"ryoku-cli/internal/sys"
)

const (
	olderUnstableBuild = "v0.94.1-beta.20.dev.11+gaaaaaaa"
	newerUnstableBuild = "v0.94.1-beta.20.dev.12+gbbbbbbb"
)

// the shape limine-snapper-sync generates (comments and paths trimmed).
const limineFixture = `timeout: 3
default_entry: Ryoku Linux/linux
/Ryoku Linux
    //linux
        comment: kernel-id=linux
        cmdline: quiet root=UUID=x rootflags=subvol=@ rw
//Snapshots
    ### Auto-generated by limine-snapper-sync
    ///2026-09-03 14:07:46
        comment: inotify-tools
        ////linux
            comment: kernel-id=linux
            protocol: efi
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/570/snapshot rw
        ////linux-cachyos
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/570/snapshot rw
    ///2026-09-02 21:00:00
        ////linux
            cmdline: quiet root=UUID=x rootflags=subvol=/@snapshots/565/snapshot rw
`

const voidLimineFixture = `default_entry: Ryoku Linux/linux6.18
/Ryoku Linux
    //linux6.18
        comment: Kernel version: 6.18.1_1
        comment: kernel-id=linux6.18
        protocol: linux
        path: boot():/vmlinuz-6.18.1_1
        module_path: boot():/initramfs-6.18.1_1.img
        cmdline: root=UUID=x rootflags=subvol=@ rw
    //Snapshots
        ### Auto-generated by limine-snapper-sync
        ///2026-10-10 02:53:22
            comment: ryoku-update
            ////linux6.18
                comment: Kernel version: 6.18.1_1
                comment: kernel-id=linux6.18
                protocol: linux
                path: boot():/limine_history/vmlinuz-6.18.1_1_sha256_deadbeef
                module_path: boot():/limine_history/initramfs-6.18.1_1.img_sha256_deadbeef
                cmdline: root=UUID=x rootflags=subvol=/@snapshots/1362/snapshot rw
`

const topLevelSnapshotsFixture = `default_entry: Ryoku Linux/linux
/Ryoku Linux
    //linux
        cmdline: rootflags=subvol=@ rw
/Snapshots
    //2026-10-10 03:00:00
        ///linux
            cmdline: rootflags=subvol=/@snapshots/1400/snapshot rw
`

const escapedSnapshotsFixture = `default_entry: Ryoku Linux/linux
/Ryoku Linux
    //linux
        cmdline: rootflags=subvol=@ rw
    //Snapshots
        ///before \#1 \/ root \\ safe
            ////linux\#fallback
                cmdline: rootflags=subvol=/@snapshots/1500/snapshot rw
`

func TestSnapshotEntryPathFindsTheNestedEntry(t *testing.T) {
	if got := snapshotEntryPath(limineFixture, "570"); got != "Ryoku Linux/Snapshots/2026-09-03 14:07:46/linux" {
		t.Fatalf("570 -> %q", got)
	}
	if got := snapshotEntryPath(limineFixture, "565"); got != "Ryoku Linux/Snapshots/2026-09-02 21:00:00/linux" {
		t.Fatalf("565 -> %q", got)
	}
	if got := snapshotEntryPath(limineFixture, "999"); got != "" {
		t.Fatalf("unknown snapshot must not match, got %q", got)
	}
	// a subvol match outside //Snapshots (the live entry) never counts
	if got := snapshotEntryPath("//Live\n    ///x\n        ////linux\n            cmdline: rootflags=subvol=/@snapshots/570/snapshot\n", "570"); got != "" {
		t.Fatalf("entry outside Snapshots matched: %q", got)
	}
}

func TestSnapshotEntryPathFindsVoidLinuxEntry(t *testing.T) {
	if got := snapshotEntryPath(voidLimineFixture, "1362"); got != "Ryoku Linux/Snapshots/2026-10-10 02:53:22/linux6.18" {
		t.Fatalf("1362 -> %q", got)
	}
}

func TestSnapshotEntryPathSupportsTopLevelSnapshotsAndEscaping(t *testing.T) {
	if got := snapshotEntryPath(topLevelSnapshotsFixture, "1400"); got != "Snapshots/2026-10-10 03:00:00/linux" {
		t.Fatalf("top-level snapshot -> %q", got)
	}
	want := `Ryoku Linux/Snapshots/before \#1 \/ root \\ safe/linux\#fallback`
	if got := snapshotEntryPath(escapedSnapshotsFixture, "1500"); got != want {
		t.Fatalf("escaped snapshot -> %q, want %q", got, want)
	}
}

func setupBootGuardPaths(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	oldPending, oldBootOK, oldNotice := pendingFile, bootOKDir, noticeFile
	oldConf, oldMarker, oldEFI, oldUID := limineConf, restoreMarker, limineLastBootedEntry, effectiveUID
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	noticeFile = filepath.Join(bootOKDir, "notice.json")
	limineConf = filepath.Join(dir, "limine.conf")
	restoreMarker = filepath.Join(dir, "limine-snapper-restore.lock")
	limineLastBootedEntry = filepath.Join(dir, "LimineLastBootedEntry")
	effectiveUID = func() int { return 0 }
	t.Cleanup(func() {
		pendingFile, bootOKDir, noticeFile = oldPending, oldBootOK, oldNotice
		limineConf, restoreMarker, limineLastBootedEntry, effectiveUID = oldConf, oldMarker, oldEFI, oldUID
	})
	return dir
}

func TestPointBootMenuAtSnapshotWritesFullPathAndClearsEFIEntry(t *testing.T) {
	setupBootGuardPaths(t)
	if err := os.WriteFile(limineConf, []byte(limineFixture), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(limineLastBootedEntry, []byte("Ryoku Linux/linux"), 0o644); err != nil {
		t.Fatal(err)
	}
	p := pendingUpdate{From: "v1.0.0", To: "v1.1.0", Snapshot: "570"}
	if err := pointBootMenuAtSnapshot(p); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(limineConf)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "default_entry: Ryoku Linux/Snapshots/2026-09-03 14:07:46/linux") {
		t.Fatalf("default was not rewritten to the full path:\n%s", raw)
	}
	if _, err := os.Stat(limineLastBootedEntry); !os.IsNotExist(err) {
		t.Fatalf("remembered EFI entry survived: %v", err)
	}
}

func TestClearLimineLastBootedEntryDoesNothingWhenAbsent(t *testing.T) {
	setupBootGuardPaths(t)
	if err := clearLimineLastBootedEntry(); err != nil {
		t.Fatal(err)
	}
}

func TestBootGuardRestoredResetsFirstKernelForBothMenus(t *testing.T) {
	tests := []struct {
		name  string
		conf  string
		entry string
	}{
		{name: "Arch", conf: limineFixture, entry: "Ryoku Linux/linux"},
		{name: "Void", conf: voidLimineFixture, entry: "Ryoku Linux/linux6.18"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			setupBootGuardPaths(t)
			if err := os.WriteFile(limineConf, []byte(test.conf), 0o644); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(restoreMarker, []byte("restored\n"), 0o644); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(limineLastBootedEntry, []byte("snapshot"), 0o644); err != nil {
				t.Fatal(err)
			}
			if err := BootGuard([]string{"--restored"}); err != nil {
				t.Fatal(err)
			}
			raw, err := os.ReadFile(limineConf)
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(string(raw), "default_entry: "+test.entry+"\n") {
				t.Fatalf("restored default =\n%s", raw)
			}
			if _, err := os.Stat(limineLastBootedEntry); !os.IsNotExist(err) {
				t.Fatalf("remembered EFI entry survived restore handling: %v", err)
			}
		})
	}
}

func TestBootGuardRestoredDoesNothingWithoutRestoreMarker(t *testing.T) {
	setupBootGuardPaths(t)
	if err := os.WriteFile(limineConf, []byte(limineFixture), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := BootGuard([]string{"--restored"}); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(limineConf)
	if err != nil {
		t.Fatal(err)
	}
	if string(raw) != limineFixture {
		t.Fatalf("config changed without restore marker:\n%s", raw)
	}
}

// Arming records the moving unstable channel while retaining the exact frozen
// builds on either side of the update.
func TestArmBootGuardRecordsChannel(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("RYOKU_REPO", "")
	t.Setenv("XDG_STATE_HOME", filepath.Join(home, ".local", "state"))
	t.Setenv("RYOKU_HOST_PKGMGR", "pacman")
	t.Setenv("XDG_CONFIG_HOME", filepath.Join(home, ".config"))

	dir := t.TempDir()
	oldPending, oldBootOK := pendingFile, bootOKDir
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	t.Cleanup(func() { pendingFile, bootOKDir = oldPending, oldBootOK })
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}

	conf := filepath.Join(dir, "pacman.conf")
	if err := os.WriteFile(conf, []byte("[options]\n\n[ryoku]\nServer = "+sys.ChannelServer(sys.ChannelTesting)+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	rel := filepath.Join(dir, "ryoku-release")
	if err := os.WriteFile(rel, []byte("RELEASE="+newerUnstableBuild+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	oldConf, oldRel := sys.PacmanConf, sys.ReleaseFile
	sys.PacmanConf, sys.ReleaseFile = conf, rel
	t.Cleanup(func() { sys.PacmanConf, sys.ReleaseFile = oldConf, oldRel })

	t.Setenv("RYOKU_UPDATE_FROM", olderUnstableBuild)
	armBootGuard("")

	raw, err := os.ReadFile(pendingFile)
	if err != nil {
		t.Fatalf("pending marker not written: %v", err)
	}
	var p pendingUpdate
	if err := json.Unmarshal(raw, &p); err != nil {
		t.Fatal(err)
	}
	if p.Channel != sys.ChannelTesting {
		t.Fatalf("recorded channel = %q, want testing", p.Channel)
	}
	if p.From != olderUnstableBuild || p.To != newerUnstableBuild {
		t.Fatalf("From/To = %q/%q, want %s/%s", p.From, p.To, olderUnstableBuild, newerUnstableBuild)
	}
}

func setupXBPSReleaseHost(t *testing.T) string {
	t.Helper()
	home := isolateHome(t)
	t.Setenv("RYOKU_HOST_PKGMGR", "xbps")
	t.Setenv("RYOKU_HOST_PKG_TABLE", filepath.Join(home, "void.tsv"))
	t.Setenv("RYOKU_RELEASE_BASE", "")
	if err := os.WriteFile(filepath.Join(home, "void.tsv"), []byte("arch\tvoid\tlanes\tnotes\nryoku-desktop\tryoku-desktop\tdesktop\trepo=ryoku\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	bin := filepath.Join(home, "bin")
	if err := os.MkdirAll(bin, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(bin, "xbps-query"), []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin)

	dir := t.TempDir()
	configDir := filepath.Join(dir, "xbps.d")
	shipped := filepath.Join(dir, "20-ryoku.conf")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(shipped, []byte("repository=https://repo.ryoku.dev/stable/void/x86_64\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("RYOKU_XBPS_CONFIG_DIR", configDir)
	t.Setenv("RYOKU_XBPS_SHIPPED_CONFIG", shipped)

	release := filepath.Join(dir, "ryoku-release")
	if err := os.WriteFile(release, []byte("RELEASE=v0.75.3-beta.20\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	oldRelease, oldIntent := sys.ReleaseFile, sys.ChannelIntentFile
	sys.ReleaseFile = release
	sys.ChannelIntentFile = filepath.Join(dir, "channel-intent")
	t.Cleanup(func() {
		sys.ReleaseFile = oldRelease
		sys.ChannelIntentFile = oldIntent
	})
	return dir
}

func capturePackageMove(t *testing.T) *[][]string {
	return capturePackageMoveSet(t, []string{"ryoku-desktop", "ryogami"})
}

func capturePackageMoveSet(t *testing.T, set []string) *[][]string {
	t.Helper()
	var calls [][]string
	oldSync, oldSet, oldServed := syncRepoForMove, ryokuSetForMove, servedSetForMove
	oldInstalled, oldSplit, oldMove := pkgInstalledForMove, splitMetaInstalled, runRyokuMove
	syncRepoForMove = func(bool) error { return nil }
	ryokuSetForMove = func() ([]string, error) { return set, nil }
	servedSetForMove = func() map[string]bool { return map[string]bool{"ryoku-desktop": true, "ryogami": true} }
	pkgInstalledForMove = func(string) bool { return true }
	splitMetaInstalled = func(string) bool { return false }
	runRyokuMove = func(set []string) error {
		calls = append(calls, ryokuMoveArgs(set))
		return nil
	}
	t.Cleanup(func() {
		syncRepoForMove, ryokuSetForMove, servedSetForMove = oldSync, oldSet, oldServed
		pkgInstalledForMove, splitMetaInstalled, runRyokuMove = oldInstalled, oldSplit, oldMove
	})
	return &calls
}

func TestArmBootGuardOnXBPSUnstableBuildChange(t *testing.T) {
	dir := setupXBPSReleaseHost(t)
	oldPending, oldBootOK := pendingFile, bootOKDir
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	t.Cleanup(func() { pendingFile, bootOKDir = oldPending, oldBootOK })
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "xbps.d", "20-ryoku.conf"), []byte("repository="+sys.VoidChannelURL(sys.ChannelTesting)+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(sys.ReleaseFile, []byte("RELEASE="+newerUnstableBuild+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	t.Setenv("RYOKU_UPDATE_FROM", olderUnstableBuild)
	armBootGuard("1362")

	raw, err := os.ReadFile(pendingFile)
	if err != nil {
		t.Fatalf("pending marker not written: %v", err)
	}
	var p pendingUpdate
	if err := json.Unmarshal(raw, &p); err != nil {
		t.Fatal(err)
	}
	if p.From != olderUnstableBuild || p.To != newerUnstableBuild || p.Channel != sys.ChannelTesting || p.Snapshot != "1362" {
		t.Fatalf("pending marker = %+v", p)
	}
}

func TestRollbackToUnstableBuildRunsXBPSMove(t *testing.T) {
	setupXBPSReleaseHost(t)
	calls := capturePackageMove(t)
	oldUpdate := runChannelUpdate
	runChannelUpdate = func() error {
		_, err := moveRyokuSetToChannel()
		return err
	}
	t.Cleanup(func() { runChannelUpdate = oldUpdate })

	if err := Rollback([]string{"--to", olderUnstableBuild}); err != nil {
		t.Fatal(err)
	}
	want := []string{"env", "RYOKU_MANAGED_UPDATE=1", "xbps-install", "-Sfy", "ryoku-desktop", "ryogami"}
	if len(*calls) != 1 || !reflect.DeepEqual((*calls)[0], want) {
		t.Fatalf("XBPS move calls = %v, want [%v]", *calls, want)
	}
	if channel := packagedChannel(); channel != olderUnstableBuild {
		t.Fatalf("XBPS channel = %q, want %q", channel, olderUnstableBuild)
	}
}

func TestBootGuardRevertsXBPSUnstableBuild(t *testing.T) {
	dir := setupXBPSReleaseHost(t)
	calls := capturePackageMove(t)
	oldPending, oldBootOK, oldNotice, oldUID := pendingFile, bootOKDir, noticeFile, effectiveUID
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	noticeFile = filepath.Join(bootOKDir, "notice.json")
	effectiveUID = func() int { return 0 }
	t.Cleanup(func() {
		pendingFile, bootOKDir, noticeFile, effectiveUID = oldPending, oldBootOK, oldNotice, oldUID
	})
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}
	p := pendingUpdate{
		From: olderUnstableBuild, To: newerUnstableBuild, Channel: sys.ChannelTesting,
		Snapshot: "1362", ArmedBoot: "earlier-boot", Boots: 1,
	}
	body, _ := json.Marshal(p)
	if err := os.WriteFile(pendingFile, body, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := BootGuard(nil); err != nil {
		t.Fatal(err)
	}
	want := []string{"env", "RYOKU_MANAGED_UPDATE=1", "xbps-install", "-Sfy", "ryoku-desktop", "ryogami"}
	if len(*calls) != 1 || !reflect.DeepEqual((*calls)[0], want) {
		t.Fatalf("XBPS revert calls = %v, want [%v]", *calls, want)
	}
	if channel := packagedChannel(); channel != olderUnstableBuild {
		t.Fatalf("XBPS revert channel = %q, want %q", channel, olderUnstableBuild)
	}
	if _, err := os.Stat(pendingFile); !os.IsNotExist(err) {
		t.Fatalf("pending marker survived successful revert: %v", err)
	}
	raw, err := os.ReadFile(noticeFile)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), `"action": "reverted"`) || !strings.Contains(string(raw), "Void untouched") ||
		!strings.Contains(string(raw), "`ryoku track unstable`") {
		t.Fatalf("revert notice = %s", raw)
	}
}

func TestBootGuardRevertsPacmanUnstableBuild(t *testing.T) {
	isolateHome(t)
	packagedConf(t, sys.ChannelTesting)
	calls := capturePackageMove(t)
	setupBootGuardPaths(t)
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}
	p := pendingUpdate{
		From: olderUnstableBuild, To: newerUnstableBuild, Channel: sys.ChannelTesting,
		ArmedBoot: "earlier-boot", Boots: 1,
	}
	body, _ := json.Marshal(p)
	if err := os.WriteFile(pendingFile, body, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := BootGuard(nil); err != nil {
		t.Fatal(err)
	}
	want := []string{"env", "SNAP_PAC_SKIP=y", "RYOKU_MANAGED_UPDATE=1", "pacman", "-S", "--needed", "--noconfirm", "--overwrite", RyokuOverwriteGlob, "ryoku-desktop", "ryogami"}
	if len(*calls) != 1 || !reflect.DeepEqual((*calls)[0], want) {
		t.Fatalf("pacman revert calls = %v, want [%v]", *calls, want)
	}
	if channel := packagedChannel(); channel != olderUnstableBuild {
		t.Fatalf("pacman revert channel = %q, want %q", channel, olderUnstableBuild)
	}
	raw, err := os.ReadFile(noticeFile)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "Arch untouched") || !strings.Contains(string(raw), "`ryoku track unstable`") {
		t.Fatalf("revert notice = %s", raw)
	}
}

func setupDNFReleaseHost(t *testing.T) string {
	t.Helper()
	home := isolateHome(t)
	t.Setenv("RYOKU_HOST_PKGMGR", "dnf")
	t.Setenv("RYOKU_RELEASE_BASE", "")
	osRelease := filepath.Join(home, "os-release")
	if err := os.WriteFile(osRelease, []byte("ID=fedora\nVERSION_ID=44\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("RYOKU_OS_RELEASE", osRelease)
	bin := filepath.Join(home, "bin")
	if err := os.MkdirAll(bin, 0o755); err != nil {
		t.Fatal(err)
	}
	writeExec(t, filepath.Join(bin, "dnf5"), "#!/bin/sh\nexit 0\n")
	writeExec(t, filepath.Join(bin, "rpm"), "#!/bin/sh\nexit 0\n")
	t.Setenv("PATH", bin)

	dir := t.TempDir()
	repo := filepath.Join(dir, "ryoku.repo")
	body := "[ryoku]\nname=Ryoku\nbaseurl=" + host.RepoURLFor(host.DNF, sys.ChannelTesting) + "\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ryoku\n"
	if err := os.WriteFile(repo, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("RYOKU_DNF_REPO_CONFIG", repo)
	release := filepath.Join(dir, "ryoku-release")
	if err := os.WriteFile(release, []byte("RELEASE="+newerUnstableBuild+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	oldRelease, oldIntent := sys.ReleaseFile, sys.ChannelIntentFile
	sys.ReleaseFile = release
	sys.ChannelIntentFile = filepath.Join(dir, "channel-intent")
	t.Cleanup(func() {
		sys.ReleaseFile = oldRelease
		sys.ChannelIntentFile = oldIntent
	})
	return dir
}

func TestBootGuardRevertsDNFUnstableBuild(t *testing.T) {
	dir := setupDNFReleaseHost(t)
	set := []string{"ryoku-desktop-0:1.2.3-1.fc44", "ryogami-0:1.2.3-1.fc44"}
	calls := capturePackageMoveSet(t, set)
	oldPending, oldBootOK, oldNotice, oldUID := pendingFile, bootOKDir, noticeFile, effectiveUID
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	noticeFile = filepath.Join(bootOKDir, "notice.json")
	effectiveUID = func() int { return 0 }
	t.Cleanup(func() {
		pendingFile, bootOKDir, noticeFile, effectiveUID = oldPending, oldBootOK, oldNotice, oldUID
	})
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}
	p := pendingUpdate{
		From: olderUnstableBuild, To: newerUnstableBuild, Channel: sys.ChannelTesting,
		ArmedBoot: "earlier-boot", Boots: 1,
	}
	body, _ := json.Marshal(p)
	if err := os.WriteFile(pendingFile, body, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := BootGuard(nil); err != nil {
		t.Fatal(err)
	}
	want := append([]string{"env", "RYOKU_MANAGED_UPDATE=1", "dnf5", "distro-sync", "-y"}, set...)
	if len(*calls) != 1 || !reflect.DeepEqual((*calls)[0], want) {
		t.Fatalf("DNF revert calls = %v, want [%v]", *calls, want)
	}
	if channel := packagedChannel(); channel != olderUnstableBuild {
		t.Fatalf("DNF revert channel = %q, want %q", channel, olderUnstableBuild)
	}
	raw, err := os.ReadFile(noticeFile)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "Fedora untouched") || !strings.Contains(string(raw), "`ryoku track unstable`") {
		t.Fatalf("revert notice = %s", raw)
	}
}

func TestBootGuardDNFSnapshotEscalationStopsWithoutLimine(t *testing.T) {
	dir := setupDNFReleaseHost(t)
	oldPending, oldBootOK, oldNotice, oldUID := pendingFile, bootOKDir, noticeFile, effectiveUID
	pendingFile = filepath.Join(dir, "update-pending.json")
	bootOKDir = filepath.Join(dir, "boot")
	noticeFile = filepath.Join(bootOKDir, "notice.json")
	effectiveUID = func() int { return 0 }
	t.Cleanup(func() {
		pendingFile, bootOKDir, noticeFile, effectiveUID = oldPending, oldBootOK, oldNotice, oldUID
	})
	if err := os.MkdirAll(bootOKDir, 0o777); err != nil {
		t.Fatal(err)
	}
	p := pendingUpdate{
		From: olderUnstableBuild, To: newerUnstableBuild, Channel: sys.ChannelTesting,
		ArmedBoot: "earlier-boot", Boots: 2,
	}
	body, _ := json.Marshal(p)
	if err := os.WriteFile(pendingFile, body, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := BootGuard(nil); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(noticeFile)
	if err != nil {
		t.Fatal(err)
	}
	text := string(raw)
	if !strings.Contains(text, `"action": "revert-failed"`) || !strings.Contains(text, "Fedora") {
		t.Fatalf("Fedora escalation notice = %s", raw)
	}
	if strings.Contains(strings.ToLower(text), "limine") {
		t.Fatalf("Fedora escalation names Limine: %s", raw)
	}
	if _, err := os.Stat(pendingFile); !os.IsNotExist(err) {
		t.Fatalf("pending marker survived terminal Fedora escalation: %v", err)
	}
}
