#!/bin/sh
exec 2>&1

. "${RYOKU_INIT_LIB:-/usr/lib/ryoku/runit}/wait-for"
load_session_env
BIN=${RYOKU_BIN_DIR:-/usr/bin}

wait_env WAYLAND_DISPLAY "${RYOKU_WAIT_WAYLAND:-60}" || exec sv down .
load_session_env
require_bin "$BIN/ryoku-palette-bridge" || exec sv down .

exec "$BIN/ryoku-palette-bridge"
