#!/bin/sh
exec 2>&1

. "${RYOKU_INIT_LIB:-/usr/lib/ryoku/runit}/wait-for"
load_session_env
BIN=${RYOKU_BIN_DIR:-/usr/bin}
_conf="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/ryoku/eq/filter-chain.conf"
wait_file "$_conf" "${RYOKU_WAIT_EQ_CONF:-60}" || exec sv down .
wait_dbus org.freedesktop.PipeWire "${RYOKU_WAIT_PIPEWIRE:-60}" || exec sv down .

exec "$BIN/pipewire" -c "$_conf"
